In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SubsetRandomSampler

import numpy as np
import csv

import matplotlib.pyplot as plt

In [14]:
from numpy import genfromtxt

class COVID19dataset(Dataset):
    def __init__(self):
        xy = genfromtxt('covid.train.csv', delimiter = ',')  # type:nparray
        xy = torch.from_numpy(xy[1:, 1:])

        self.x = xy[]

tensor([[ 1.0000,  0.0000,  0.0000,  ..., 53.9915, 43.6042, 20.7049],
        [ 1.0000,  0.0000,  0.0000,  ..., 54.1855, 42.6658, 21.2929],
        [ 1.0000,  0.0000,  0.0000,  ..., 53.6371, 42.9724, 21.1667],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ..., 67.7312, 38.7407, 12.6134],
        [ 0.0000,  0.0000,  0.0000,  ..., 67.7951, 38.5951, 12.4772],
        [ 0.0000,  0.0000,  0.0000,  ..., 68.2841, 38.4538, 11.8117]],
       dtype=torch.float64)


In [15]:
data = []
with open('covid.train.csv', 'r') as fp:
    data = list(csv.reader(fp))
    data = np.array(data[1:])[:, 1:].astype(float)
    # print(data)

feats = list(range(40))
feats.append(57)
feats.append(75)

target = data[:, -1]  # target: 除了第三天的結果
data = data[:, feats]  # data: 40種狀態 + 第一、二天的結果
# print(data)

[[ 1.         0.         0.        ...  0.        19.586492  20.1518381]
 [ 1.         0.         0.        ...  0.        20.1518381 20.7049346]
 [ 1.         0.         0.        ...  0.        20.7049346 21.2929114]
 ...
 [ 0.         0.         0.        ...  1.        13.0088534 12.7256383]
 [ 0.         0.         0.        ...  1.        12.7256383 12.6134414]
 [ 0.         0.         0.        ...  1.        12.6134414 12.4772268]]
